settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-cloudflare-com-tw
    name: www.hccc.com.tw
    description: 'hccc'
    url: 'https://www.hccc.com.tw'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www-altaistwe-com
    name: www.altaistw.com
    description: 'hccc'
    url: 'https://www.altaistw.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
